### ISSUE TITLE
Stack?

### ISSUE THREAD

**Issue by FrankBoesing** [PaulStoffregen/teensy41_ethernet#1]
Would be good to know what the plan is..

- port a existing Stack? (I would prefer that - lwIP is used by other Arduinos)
Tom worked on that, and it works already.

- write a own stack.. oh my.. :)

**Comment by PaulStoffregen** [comment]
I don't have much of a plan at this point.

But I am kinda hoping to see code and a readme with step-by-step instructions for running the speed tests.  :)

**Comment by manitou48** [comment]
I tried to drag my t41ether folder (lwip lib and test sketches) into the upload files box, but it complained that it was more than 100 files and wouldn't accept the folder .... 
Is there a better way?  or is this not the place for my t41ether folder?

**Comment by Defragster** [comment]
Can you clone the REPO to your desktop and create an \Examples folder and put your stuff under there with Github Desktop ?

**Comment by Defragster** [comment]
That worked from my windows github desktop

**Comment by manitou48** [comment]
So I should clone this on my machine, then add my folder to my cloned copy, and then do a pull request?  i assume if i did a fork of this, it would end up public in my repository -- defeating the privacy goal.   i am not github fluent.

**Comment by mjs513** [comment]
Tom

You want me to give it a try.  I use github desktop and what I do is clone it to desktop paste what I want in and upload directly

**Comment by KurtE** [comment]
I could be wrong but I believe if you fork a private project your clone is private as well...  at least that was what happened several years ago

**Comment by Defragster** [comment]
As a clone to personal machine that doesn’t put it on github web at all as an account repository.

And when FORKED online – it maintains it as Private repository on web.  And in the ‘Settings’ that shows – takes a click to make public.

Seems to be safe either way.


From: KurtE<mailto:notifications@github.com>        Sent: Monday, February 24, 2020 4:10 PM

I could be wrong but I believe if you fork a private project your clone is private as well... at least that was what happened several years ago
